---
title       : Coursera Developing Data Products
subtitle    : assesment slides
author      : Ricardo Manzano
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Description

The assesment use the galton data of parents height to compare your height with galton data. 
It shows a red line with your height inside the parents histogram and show another green line with the data mean. 
It writes also the difference between them.

--- .class #id 

## Input

The input should be your height in inches.

--- .class #id 


## Output

The output is an histogram of galton parents data with two vertical lines:
One green line with the mean of the data and another red line with your height (70 in example).

```{r echo=FALSE}
library(UsingR)
data(galton)
hist(galton$parent,main="Compare your height with galton parents data",xlab="parents height")
height=70
lines(c(mean(galton$parent), mean(galton$parent)), c(0, 200),col="green" ,lwd=5)
lines(c(height, height), c(0, 200),col="red",lwd=5)
```

--- .class #id 

## Steps

The steps are:

1. Download the files to your PC.
2. From RStudio change working directory to downloaded directory.
3. run code.R lines
4. Put url showed in console in a web browser

--- .class #id 

## References

This data was found at http://www.bun.kyoto-u.ac.jp/~suchii/galton86.html.

See also the data.set father.son which was found from http://stat-www.berkeley.edu/users/juliab/141C/pearson.dat.

--- .class #id 
